[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    esphome/ESPAsyncWebServer-esphome@^3.1.0
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_EVENT_RUNNING_CORE=1
